### ISSUE TITLE
run the N-Tidigits dataset

### ISSUE THREAD

**Issue by chenjiefighting** [nmi-lab/decolle-public#21]
Your work is wonderful. I want run the N-Tidigits dataset, but there was something wrong, and the parameters of this dataset are not known, could you tell me these?

**Comment by eneftci** [comment]
Hi @chenjiefighting,
Can you be more specific with "something wrong". There is no optimized parameters for N-Tidigits but with the latest version of torchneuromorphic (from github, not pip) you should be able to run it. In order to change the dataset in existing scripts, modify the yml file line:

`dataset: torchneuromorphic.dvs_gestures.dvsgestures_dataloaders`

to 

`dataset: torchneuromorphic.ntidigits.ntidigits_dataloaders`

**Comment by chenjiefighting** [comment]
Thanks for your reply, @eneftci . I modify `dataset：torchneuromorphic.ntidigits.ntidigits_dataloaders` and `input_shape：64, 32, 32` , it worked.
